### ISSUE TITLE
Shape of <images batch>

### ISSUE THREAD

**Issue by sunija-dev** [sugyan/tf-dcgan#2]
What should be the shape of <images batch>?

Is it (<image_x_size>, <image_y_size>, <image_dimensions>, <batch_size>) ?
Would the default then be (64, 64, 3, 128)?

Thanks!

**Comment by sugyan** [comment]
Oops. I didn't write about it.
It's the same as the argument used in the functions of `tf.image`, `[batch, height, width, channel]`.
https://www.tensorflow.org/api_docs/python/image/

So the default will be `(128, 64, 64, 3)`.

Thanks!

**Comment by sugyan** [comment]
So the default will be `(128, 64, 64, 3)`.

**Comment by sunija-dev** [comment]
Thanks, that worked perfectly! :)
And thanks for the code in general. Much easier to understand and work with than the one provided with the paper. : 3
