### ISSUE TITLE
Feature matching?

### ISSUE THREAD

**Issue by christiancosgrove** [sugyan/tf-dcgan#6]
I saw your YouTube video showing face generation with feature matching. Has it been removed in the TensorFlow 1.0 version of this code?

**Comment by sugyan** [comment]
Ah, yes.
Since feature matching is not included in the original DCGAN paper, I changed it so that users can add them yourself.
Please see https://github.com/sugyan/face-generator/blob/4dbfcd3ba8bc166dd85666220461d5dee1a5776e/train.py#L50-L54
